// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowButton: typeof import('./components/ArrowButton.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    Preload: typeof import('./components/Preload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
